version: '3.4'

services:
  ntu.iot.web:
    image: ${DOCKER_REGISTRY-}ntuioProd
    build:
      context: .
      dockerfile: NTU.IoT.Web/Dockerfile
    networks:
      - iot_iot
    ports:
      - "2377:2377"
networks:
  iot_iot:
    external:
      name: iot_iot


